### ISSUE TITLE
plugin结构定义

### ISSUE THREAD

**Issue by githoniel** [gem-mine/rc-slate#6]
# 插件结构

当前插件的结构，输出的是一个对象
```
const plugin = {
  name: 'plugin name',
  tooltip: 'plugin tooltip',
  icon: (props) => {
    // 内部传递以下参数供组件使用
    // const { name, tooltip, editor, prefixCls, locale } = props
    return <ToolbarIcon />
  },
  hooks: {
    onCommand: () => {},
    onDrop: () => {},
  }
}
```

对象插件，对于多实例的输出较为繁琐，而且如果采用return obj的方式，则有点函数重复定义

所以建议改成Class实现

# 插件中间层

通用中间层支持，富文本插件大概率实现不了完美正交，需要提供插件是否安装的检测

# 插件机制
 
由于slate API覆写现在改成了类似洋葱结构的函数调用方式，对于插件而言，要求每次保存一次原始方法，较为繁琐。

目前的FnList效果可以，是否为with内覆写的函数也提供支持?

还有如果插件不正交，需要提供下FnList供其读取，对于后续操作应当都是可控的

# 插件UI部分

目前插件结构提供了toolbar区域按钮的字段式注册，但是实际上状态不要太多，disable/hover等等，这块最好划分区域，让用户自己去render，提供JSX.element过来

还有依赖范围内还可能会有sidebar之类， 可能还需要一个renderInEditor的帮助函数

**Comment by gyh9457** [comment]
通过 class 实现
升级到 0.5x 版本后，插件结构有一些调整：去除 hooks(slate 调整了插件形式)，增加 `renderElement` `renderLeaf`，计划增加 `with` 覆盖类似 `withReact` 这样的插件能力。

```js
class Plugin {
   constructor(props) {
    const { name, tooltip, icon, renderLeaf, renderElement, with } = props
    this,name = name
    this.tooltip = tooltip
    ......
    ......
  }
}

const plugin = new Plugin({
  name: 'plugin name',
  tooltip: 'plugin tooltip',// 支持 (locale) => string 的形式
  icon: (props) => {
    // 内部传递以下参数供组件使用
    // const { name, tooltip, editor, prefixCls, locale } = props
    return <ToolbarIcon />
  },
  renderLeaf: ({ attributes, children, leaf }) => Element,
  renderElement: ({ attributes, children, element}) => Element,
  with: (eidtor) => editor
})
```

同时需要考虑使用者怎么接触到 onKeyDown , onBeforeInput 这些事件处理函数，在一些情况下需要通过这些事件进行特殊处理

**Comment by githoniel** [comment]
UI和行为分离只能靠开发者自觉了，这个没太好办法限制

onKeyDown/onBeforeInput依旧类似目前的FnList方法挨个冒泡传递就好了

**Comment by gyh9457** [comment]
> # 插件结构
> 当前插件的结构，输出的是一个对象
> 
> ```
> const plugin = {
>   name: 'plugin name',
>   tooltip: 'plugin tooltip',
>   icon: (props) => {
>     // 内部传递以下参数供组件使用
>     // const { name, tooltip, editor, prefixCls, locale } = props
>     return <ToolbarIcon />
>   },
>   hooks: {
>     onCommand: () => {},
>     onDrop: () => {},
>   }
> }
> ```
> 
> 对象插件，对于多实例的输出较为繁琐，而且如果采用return obj的方式，则有点函数重复定义
> 
> 所以建议改成Class实现
> 
> # 插件中间层
> 通用中间层支持，富文本插件大概率实现不了完美正交，需要提供插件是否安装的检测
> 
> # 插件机制
> 由于slate API覆写现在改成了类似洋葱结构的函数调用方式，对于插件而言，要求每次保存一次原始方法，较为繁琐。
> 
> 目前的FnList效果可以，是否为with内覆写的函数也提供支持?
> 
> 还有如果插件不正交，需要提供下FnList供其读取，对于后续操作应当都是可控的
> 
> # 插件UI部分
> 目前插件结构提供了toolbar区域按钮的字段式注册，但是实际上状态不要太多，disable/hover等等，这块最好划分区域，让用户自己去render，提供JSX.element过来
> 
> 还有依赖范围内还可能会有sidebar之类， 可能还需要一个renderInEditor的帮助函数

toolbar 由用户自定义，在fish层不是很合适，提供一个默认实现，同时开放自定义的接口？

**Comment by githoniel** [comment]
# Toolbar抽象

Toolbar渲染的一大难题就是group问题，添加插件的时候直接按照group给予插件，还是单独给一个toolbarGroups字段用于组织分组？

**Comment by gyh9457** [comment]
tollbarGroups 给个二维数组用于分组？
目前是先 addPlugin，再设置 toolbar。改为 先确定 toolbar，再根据需要的插件去 addPlugin?

**Comment by gyh9457** [comment]
目前的插件是一个包一个包的实现，比如说 `图片上传` 插件放在 `rc-slate-plugin-image` 包内，
是否要改成按照 `leaf` `element` 的类型来分成两个包 `rc-slate-plugin-leaf` `rc-slate-plugin-element`。所有子类都放在这两个包下？

**Comment by gyh9457** [comment]
plugin 参数传递问题：
目前的 pluginOptions 是全局的，比如说
```js
  const pluginOptions = { toolBarGroupIndex: 1 }
```
这个参数会被所有插件接收。

是否将 pluginOptions 设计成这样的形式 `{ link: {}, image: {} }`,方便不同的插件自定义参数

```js
    slatePlugin.addPlugin([
      ...Object.values(defaultPlugins),
      ...customPlugins || []
    ], {
      link: {
        onClick: (plugin) => {
          const { Modal } = (window as any).fish
          console.log(plugin)
          Modal.confirm({
            title: '请输入url'
          })
        }
      }
    })
```

```js
  addPlugin(plugins: ISlatePlugin[] | ISlatePlugin, pluginOptions?: any) {
    const pluginArray = Array.isArray(plugins)
      ? plugins : [plugins]
    pluginArray.forEach((plugin) => {
      if (typeof plugin === 'function') {
        // TODO 临时提供兼容解决，等全部迁移了再说
        // @ts-ignore
        plugin = new plugin({ // eslint-disable-line no-param-reassign, new-cap
          ...pluginOptions[(plugin as any).name], // 这里根据插件名称传递参数
          editor: this.editor
        })
      }
      if (this.pluginMap.has(plugin.name)) {
        // TODO: remove when product
        console.warn(`plugin ${plugin.name} already exists, the original plugin will be overwritten.`)
      }
      this.pluginMap.set(plugin.name, plugin)
      if (this.toolbar) {
        this.toolbar.addItem(plugin)
      }
    })
    return this
  }

@githoniel 
```

**Comment by githoniel** [comment]
现在可以这样
```js
slatePlugin
	.addPlugin(PluginA, pluginAOption)
    .addPlugin(PluginB, pluginBOption)
    .addPlugin(PluginC, pluginCOption)
```
你描述的方法需要预知插件的name，开发者随便写name就没法设置了

**Comment by gyh9457** [comment]
这样子在 rc-slate-component 这层没问题，在fish这层要怎么传呢，fish 这层拿不到这个插件

**Comment by githoniel** [comment]
从目前的需求来看, 要实现以下几点
1. 用户可以随意添加插件，可以修改插件配置
2. 用户可能需要访问`slate editor`实例，`editor.focus()`之类的函数很可能需要被使用
3. 自带的小插件，全部独立发布和配置有点蛋疼，数量不少

可以这样

1. 插件延迟初始化: 当前slatePlugin的插件是`addPlugin`的时候就初始化，我们需要调整成lazy模式，`addPlugin`的时候，将插件Class和options缓存到`pluginMap`，不立刻初始化插件实例， 而是等`slatePlugin.apply`的时候再生成插件实例
2. 基于1的修改，我们可以增加`slatePlugin.tap`函数，在`slatePlugin.apply`之前修改参数，当然这要求`plugin.name`必须是可知的，这个就没什么办法

```typescript
type tap = (pluginName, pluginOptions) => void
```

3. export接口如下

```ts
interface GemSlateFactoryConstructor {
  /**
   * useBuiltPluginMode
   *  - base模式只提供文本类插件配置
   *  - full模式提供一些复杂组件
   */
  new ({
    usebuiltPlugin: 'base' : 'full'
  }): GemSlateFactory
}

interface GemSlateFactory {
  /**
   * 可以获取到SlatePlugin实例，任意添加插件，也可以设置选项
   */
  slatePlugin: SlatePlugin

  /**
   * 内置插件列表，包含我们目前开发的所有插件
   * 也可以考虑分点包发布到NPM，到时候用户自己去import
   */
  builtInPlugins: {
    [key: string]: ISlatePlugin
  }
  /**
   * 当前slate实例
   */
  slate: Editor
  /**
   * 获取SlateComponent组件，只有首次get的时候才会出初始化插件
   * 
   * 第一次获取的时候生成组件，第二次为缓存值
   * 
   * useBuiltPluginMode
   *  - base模式只提供文本类
   *  - full模式提供一些复杂组件，全部用默认设置
   */
  get SlateComponent: ({
    useBuiltPluginMode: 'base' : 'full'
  }) => SlateComponent
}
```
用户可以这样玩
```ts
const gemSlateFactory = new GemSlateFactory({
  usebuiltPlugin: 'full'
})
gemSlateFactory.slatePlugin
   .add(MyPlugin, myPluginOptions)
   .tap('image', (options) => {
       options.uploadImage = .....
   })
```

我不太熟悉React社区的API设计风格，@gyh9457 看看是否合适

**Comment by githoniel** [comment]
> 目前的插件是一个包一个包的实现，比如说 `图片上传` 插件放在 `rc-slate-plugin-image` 包内，
> 是否要改成按照 `leaf` `element` 的类型来分成两个包 `rc-slate-plugin-leaf` `rc-slate-plugin-element`。所有子类都放在这两个包下？

目前分包只是插件的组织模式，并没有发布到NPM，拆细点方便commmit/changelog生成的时候明确是改了什么插件，这个合并看起来没什么变化

我们会考虑把这些子包也发布出去么？有发布的话的话合包才有意义。对用户而言可能关心的是插件的用途，如果将来有发布出去的话，合一个rc-slate-base-plugins包，包含一些必备的基础插件，这个看起来挺好的

**Comment by gyh9457** [comment]
base 和 full 可以说的更细一点吗 不是很理解

**Comment by gyh9457** [comment]
> > 目前的插件是一个包一个包的实现，比如说 `图片上传` 插件放在 `rc-slate-plugin-image` 包内，
> > 是否要改成按照 `leaf` `element` 的类型来分成两个包 `rc-slate-plugin-leaf` `rc-slate-plugin-element`。所有子类都放在这两个包下？
> 
> 目前分包只是插件的组织模式，并没有发布到NPM，拆细点方便commmit/changelog生成的时候明确是改了什么插件，这个合并看起来没什么变化
> 
> 我们会考虑把这些子包也发布出去么？有发布的话的话合包才有意义。对用户而言可能关心的是插件的用途，如果将来有发布出去的话，合一个rc-slate-base-plugins包，包含一些必备的基础插件，这个看起来挺好的

如果不发布的话，发布的形式是什么样的，没搞过这种。
我一开始以为都要发布出去，如果不需要的话，那就保持现在这样，发布出去的包要加个 @gem-mine  的 scope

**Comment by githoniel** [comment]
> base 和 full 可以说的更细一点吗 不是很理解

模式在构造函数传入
```ts
const gemSlateFactory = new GemSlateFactory({
  usebuiltPlugin: 'simple'
})
```
那么类new的时候就根据模式，给`gemSlateFactory.slatePlugin`添加了一堆默认的插件和参数。

比如可以定义`simple`模式，包含`mark`/`hr`/`align`插件。则上面初始化后，`gemSlateFactory.slatePlugin`就已经包含了这三个插件和插件的配置，然后用户可以在这个基础上，补充插件或者修改一下插件配置

> 如果不发布的话，发布的形式是什么样的，没搞过这种。
> 我一开始以为都要发布出去，如果不需要的话，那就保持现在这样，发布出去的包要加个 @gem-mine  的 scope

1. 不发布插件包的话，把这些子包的入口全部import到`rc-slate-component`主包中再export出去，这样子只发布主包到`npm`上出去给用户就可以了
2. 发布插件包的话，目前`package/*`下的包独立构建后，全部发布到npm，让用户自己去import玩

**Comment by githoniel** [comment]
> > > 目前的插件是一个包一个包的实现，比如说 `图片上传` 插件放在 `rc-slate-plugin-image` 包内，
> > > 是否要改成按照 `leaf` `element` 的类型来分成两个包 `rc-slate-plugin-leaf` `rc-slate-plugin-element`。所有子类都放在这两个包下？
> > 
> > 
> > 目前分包只是插件的组织模式，并没有发布到NPM，拆细点方便commmit/changelog生成的时候明确是改了什么插件，这个合并看起来没什么变化
> > 我们会考虑把这些子包也发布出去么？有发布的话的话合包才有意义。对用户而言可能关心的是插件的用途，如果将来有发布出去的话，合一个rc-slate-base-plugins包，包含一些必备的基础插件，这个看起来挺好的
> 
> 如果不发布的话，发布的形式是什么样的，没搞过这种。
> 我一开始以为都要发布出去，如果不需要的话，那就保持现在这样，发布出去的包要加个 @gem-mine 的 scope

话说你不起个产品名字吗，随便想个喜欢的啊

**Comment by githoniel** [comment]
目前发现 `Editable` 的 props.onDOMBeforeInput 可能需要提供BailHook出去

**Comment by githoniel** [comment]
done
