### ISSUE TITLE
rc-slate-plugin-image

### ISSUE THREAD

**Issue by githoniel** [gem-mine/rc-slate#8]
# inline/block模式

根据同定位产品来看，大部分都采用了block模式，仅有部分支持inline模式，考虑到inline模式潜在的光标处理问题，暂时采用固定的block格式，后面再考虑是否支持inline模式

# 光标定位

暂时只考虑block模式，block模式的光标定位规则如下

1. 插入图片后，光标位于图片之后，如果在文字间插入则split_node
2. 光标移动时候，图片应当视为一个block，光标在图片之后时应当能删除图片

# 图片URL

由于本地图片上传需要服务器支持，除非使用对保存极不友好的inline base64方式实现，应让插件初始化的时候提供upload参数

# caption

卡片式图片支持, 支持下方设置文件简介

# 图片上传进度条

图片上传CDN需要一个进度条, 需要成功失败处理

**Comment by githoniel** [comment]
目前已经实现功能如下

- 支持base64 inline模式
- 支持asyncUploadImage模式
- 支持图片进度信息显示
- 支持图片失败后重新尝试传递
- 支持图片上传过程中schema变化
- 支持图片上传过程中页面刷新
- 中间状态不会污染schema

还存在问题

- 大文件base64 inline很卡
- drop/drag会复制图片，过于诡异
- 选中图片按delete/backspace无法删除
- 选中图片会闪烁

**Comment by gyh9457** [comment]
表格中禁止上传图片？

**Comment by githoniel** [comment]
> 表格中禁止上传图片？

#7 统一处理toolbarItem的disable问题
